# Generated by Django 3.2.9 on 2022-01-29 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PermisosPorRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.BooleanField(default=False, verbose_name='Permiso Ver')),
                ('editar', models.BooleanField(default=False, verbose_name='Permiso Editar')),
                ('eliminar', models.BooleanField(default=False, verbose_name='Permiso Eliminar')),
                ('modificar', models.BooleanField(default=False, verbose_name='Permiso Modificar')),
                ('permiso', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos', verbose_name='Permiso')),
                ('rol', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.rol', verbose_name='Rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
