# Generated by Django 3.2.9 on 2022-01-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
