# Generated by Django 3.2.9 on 2022-01-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisosporrol',
            name='permiso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos', verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='permisosporrol',
            name='rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
