# Generated by Django 3.2.9 on 2022-02-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20220129_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisosporrol',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='permisosporrol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='PermisosPorRol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
