# Generated by Django 3.2.9 on 2022-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20211129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='identificacion',
            field=models.BigIntegerField(verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
