# Generated by Django 3.2.9 on 2021-11-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('descripcion', models.CharField(default='No indicado', max_length=155, verbose_name='Descripción')),
            ],
        ),
    ]
