# Generated by Django 3.2.9 on 2021-11-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('inventarios', '0003_productos_codigoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='categorias.Categorias', verbose_name='Categoria'),
        ),
    ]
