# Generated by Django 3.2.9 on 2022-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeBackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='detalle',
            field=models.CharField(max_length=100, verbose_name='Detalle del parametro'),
        ),
    ]
